### PR TITLE
Generation thread now checks if it is already running before starting

### LINKED ISSUE #77: Plants spreading seem to easily overwhelm the engine
Bugs (mesh disappearing / godot crashing) appear already at plant speedup x5. On the other hand everything else x20 and plants in real time works fine.

### PR DESCRIPTION
**Pull request by JamesHinshelwood**
Fixes #77

### CODE REVIEW

**Comment by adam-kucz** [comment]
split personality case?

**Comment by adam-kucz** [comment]
Does every chunk have its own thread? That's a lot of threading

**Comment by AdamSKucz** [comment]
also, add access modifiers, pls

File: Scripts/World/Chunk.cs [hunk 1]
```diff
@@ -19,6 +19,8 @@ public class Chunk : Spatial
     SurfaceTool surfaceTool = new SurfaceTool();
     SpatialMaterial material = new SpatialMaterial();
 
+    System.Threading.Thread generationThread;
```
Comment (adam-kucz) [inline Scripts/World/Chunk.cs]: access modifiers for every field please?

Comment (JamesHinshelwood) [reply Scripts/World/Chunk.cs]: default private 😉

**Comment by JamesHinshelwood** [comment]
Yeah, not sure what best way I should do it

File: Scripts/World/Chunk.cs (hunk 1 above)
Comment (adam-kucz) [reply Scripts/World/Chunk.cs]: still, would be nicer to see it, and `using System.Threading` would look nicer

File: Scripts/World/Chunk.cs [hunk 2]
```diff
@@ -71,18 +73,21 @@ public override void _Process(float delta)
...
+            generationThread.Abort();
+        
+        generationThread = new System.Threading.Thread(() =>
         {
             GenerateSurface();
             generationFinished = true;
         })
         {
-            Priority = System.Threading.ThreadPriority.Lowest
+            Priority = System.Threading.ThreadPriority.Highest
```
Comment (adam-kucz) [inline Scripts/World/Chunk.cs]: why?

File: Scripts/World/Chunk.cs (hunk 1 above)
Comment (JamesHinshelwood) [reply Scripts/World/Chunk.cs]: Godot defines a Thread class though 😡

**Comment by adam-kucz** [comment]
I tried spamming clicks as fast as I could, still not falling through the world (although I managed to make the chunk disappear for a split second).

Well done.

File: Scripts/World/Chunk.cs (hunk 2 above)
Comment (JamesHinshelwood) [reply Scripts/World/Chunk.cs]: The lag was caused by the overhead of Godot things which have to be in main thread, so I thought its best to get the generation done asap, since it doesn't hold up the player moving or anything

**Comment by adam-kucz** [comment]
lots of grass doesn't break it either

**Comment by adam-kucz** [comment]
but there seem to be some strange bug with textures, as if red rock is still rendered under grass:
image
do we know anything about it?

File: Scripts/World/Chunk.cs (hunk 1 above)
Comment (adam-kucz) [reply Scripts/World/Chunk.cs]: maybe there is a reason it does, have you read what Godot threads are?

Comment (adam-kucz) [reply Scripts/World/Chunk.cs]: and at least do `using ST = System.Threading;` and then `ST.Thread`

**Comment by JamesHinshelwood** [comment]
I think this is more to do with textures - the one next to it in the atlas is leaking or some shit

File: Scripts/World/Chunk.cs (hunk 1 above)
Comment (JamesHinshelwood) [reply Scripts/World/Chunk.cs]: Ok sure, and yeah you can use either Godot threads or C# ones depending on what you need.
I assumed C# threads would be more stable, maybe with error messages other than '!E' is true.

**Review by adam-kucz — APPROVED** [review]
